/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'Hedgeplus',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};


module.exports = {
  docs: [
    {
      type: 'category',
      label: 'INTRODUCTION',
      items: [
        'docs/Introduction/Overview.md',
        'docs/Introduction/Challenges.md',
        'docs/Introduction/Solution.md',
      ],
    },
    {
      type: 'category',
      label: 'FEATURES',
      items: [
        'docs/Features/ Autonomous.md',
        'docs/Features/AI-Powered-Trading-Signals.md',
        'docs/Features/Crypto-Assets-Investment-Fund.md',
        'docs/Features/Inner-Circle-Altcoins-Trading.md',
        'docs/Features/MetaVerse-NFT-Game.md',
        'docs/Features/Peer-to-Peer-OTC-Exchange.md',
        'docs/Features/Zero-percent-interest-loans.md'
      ],  
    },
    {
      type: 'category',
      label: 'HINGES TOKEN',
      items: [
        'docs/Hinges-Token/Token-Utility.md',
        'docs/Hinges-Token/Token-Economics.md',
        'docs/Hinges-Token/Vesting-Schedule.md',
        'docs/Hinges-Token/Roadmap.md',
      ],  
    },
    {
      type: 'category',
      label: 'USER GUIDES',
      items: [
        'docs/User-Guides/Staking.md',
        'docs/User-Guides/Provide-Liquidity.md',
      ],  
    },
    {
      type: 'category',
      label: 'RESOURCES',
      items: [
        'docs/Resources/Deployed-Contract.md',
        'docs/Resources/Roadmap.md',
        'docs/Resources/Code-Contributors.md',
        'docs/Resources/Referral-Program.md',
        'docs/Resources/FAQ.md',
        'docs/Resources/Brand-Assets.md',
        'docs/Resources/Blog.md',
      ],  
    },
    {
      type: 'category',
      label: 'SECURITY',
      items: [
        'docs/Security/Audit.md',
        'docs/Security/Bug-Bounty-Program.md',
      ],  
    },
    {
      type: 'category',
      label: 'TEAM',
      items: [
        'docs/Team/About-Us.md',
        'docs/Team/Collaborate-with-US.md',
      ],  
    },
    '/Fractional-Co-Owned-Real-Estate/Fractional-Co-Owned-Real-Estate.md',
    '/Important-Notice/Important-Notice.md',
    '/Hinges-Vesting/Hinges-Vesting.md'
  ],
};

